### ISSUE TITLE
No .nvmrc file found

### ISSUE THREAD

**Issue by lopesdasilva** [BausCode/ops-codeship-react-native-android#1]
Hi I'm trying to use your build, but i'm getting this error:
No .nvmrc file found
On the command: 
nvm use || nvm install

Thanks

**Comment by jamesearl** [comment]
No problem, I'll add an .nvmrc, but you should feel to change the version to match your needs.

**Comment by jamesearl** [comment]
@lopesdasilva should be good to go with a default node version of 6.5.0, which is what I most recently used this buildpack on.
