### ISSUE TITLE
missing link

### ISSUE THREAD

**Issue by lopesdasilva** [BausCode/ops-codeship-react-native-android#3]
Hi i'm getting this error:

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/home/rof/.nvm/versions/node/v6.5.0/bin/node" "/home/rof/.nvm/versions/node/v6.5.0/bin/npm" "run" "link"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! missing script: link

can you please help ?
Thanks for your support

**Comment by jamesearl** [comment]
@lopesdasilva This is an issue specific to the version of react-native that you're using. Does your package.json have a `link` script in it? If not, try adding one, similar to this:

``` js
//...

"scripts": {
  //...
  "link": "node node_modules/react-native/local-cli/cli.js link"
}
```

**Comment by lopesdasilva** [comment]
Thanks! 
You can close this.
It's working now :)

**Comment by jamesearl** [comment]
Woot!
